# Generated by Django 5.0.3 on 2024-03-20 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('question', models.ManyToManyField(related_name='answers', to='Questioner.question', verbose_name='Вопрос')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(related_name='questions', to='Questioner.survey', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_question', to='Questioner.question', verbose_name='От какого вопроса')),
                ('to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_question', to='Questioner.question', verbose_name='К какому вопросу')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='Questioner.survey', verbose_name='В каком опросе')),
            ],
        ),
    ]
